displayMainMenu :-
  nl,nl,nl,
  write('//===========================================================\\\\'), nl,
  write('||                                                           ||'), nl,
  write('||    _____                                                  ||'), nl,
  write('||   |      \\                                                ||'), nl,
  write('||   |   _   |    _____    __ ___   __    ____     _____     ||'), nl,
  write('||   |  | |  |  /  _   \\  |   _   \\   |  /  _ \\   /     \\    ||'), nl,
  write('||   |  |_|  | |  |_|   | |  | |  ||  | |  ___/  |   ()  |   ||'), nl,
  write('||   |______/   \\____/|_| |__| |__||__|  \\____/   \\_____/    ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                     Select an option:                     ||'), nl,
  write('||                                                           ||'), nl,
  write('||            =>  (_1_)   1 Vs 1                             ||'), nl,
  write('||            =>  (_2_)   1 Vs Computer                      ||'), nl,
  write('||            =>  (_3_)   Computer 1 Vs Computer             ||'), nl,
  write('||            =>  (_4_)   Change Level                       ||'), nl,
  write('||            =>  (_5_)   Exit                               ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('||                                                           ||'), nl,
  write('\\\\===========================================================//'), nl,
  nl,nl,nl.
